//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int AdminId { get; set; }
        public string AdminName { get; set; }
        public string AdminAddress { get; set; }
        public string AdminPhone { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Type { get; set; }
        public string EmailAdmin { get; set; }
    }
}
