//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
        [DisplayName("Mã đơn hàng")]
        public int OrderId { get; set; }
        [DisplayName("Mã khách hàng")]
        public Nullable<int> CustomerId { get; set; }
        [DisplayName("Ngày đặt hàng")]
        public Nullable<System.DateTime> OrderDate { get; set; }
        [DisplayName("Ngày giao hàng")]
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        [DisplayName("Địa chỉ nhận hàng")]
        public string Address { get; set; }
        [DisplayName("Người nhận")]
        public string Recipient { get; set; }
        [DisplayName("Số điện thoại nhận hàng")]
        public string RecipientPhone { get; set; }
        [DisplayName("Tình trạng đơn hàng")]
        public Nullable<bool> OrderState { get; set; }
        [DisplayName("Giá tiền")]
        public Nullable<decimal> OrderPrice { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual OrderDetail OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    
}
}
